YAML configs updated

diff --git a/.github/workflows/auto_check_build_on_main.yml b/.github/workflows/auto_check_build_on_main.yml
--- a/.github/workflows/auto_check_build_on_main.yml
+++ b/.github/workflows/auto_check_build_on_main.yml
@@ -16,8 +16,24 @@ defaults:
     shell: bash
 
 jobs:
+  check-author:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check last commit author
+        run: |
+          if [ "${{ github.event.head_commit.author.username }}" == "${{ vars.TECHNICAL_USER }}" ]; then
+            echo "The last author is '${{ github.event.head_commit.author.username }}'. The workflow is going to be aborted."
+            exit 1
+          fi
+
   # Build job
   build:
+    needs: [check-author]
     runs-on: ubuntu-latest
     env:
         HUGO_VERSION: 0.122.0
